### PR TITLE
Integrate ITREX to support int8 model on the CPU-only devices

### PR DESCRIPTION
**Pull request by yiliu30**
1st PR for https://github.com/stochasticai/xTuring/issues/264 to integrate [Intel-Extension-for-Transformers](https://github.com/intel/intel-extension-for-transformers) to support int8 model on the CPU-only devices.

### Usage

```python
from xturing.models import BaseModel

# Auto detect the device and load int8 with Itrex if cpu-only
model = BaseModel.create("llama2_int8")

# Inference model with Itrex's highly optimized kernels
output = model.generate(texts=["Why are the LLM models important?"])
print(output)
```

### TODO

- [x] Load model with Itrex for CPU-only device
- [x] Add example (gpt2, llama2)
- [ ] Add UT (WIP)
- [ ] Doc

@StochasticRomanAgeev

### CODE REVIEW

**Comment by yiliu30** [comment]
Hi @StochasticRomanAgeev, could you please take the time to conduct a preliminary review?

**Comment by yiliu30** [comment]
Hi @StochasticRomanAgeev @tushar2407 @MarcosRiveraMartinez, could you please take your time to review the PR, thanks :)

**Comment by StochasticRomanAgeev** [comment]
Hi @yiliu30,
Done merging, thanks for doing this integration!

**Comment by StochasticRomanAgeev** [comment]
It would be great if you could include a brief description of update into CPU inference section in the README. I intend to provide this enhancement in a subsequent PR.

**Comment by yiliu30** [comment]
> It would be great if you could include a brief description of update into CPU inference section in the README. I intend to provide this enhancement in a subsequent PR.

Sure, I'll add an introduction in a follow-up PR soon :)

**Pull request merged**
